# This file can be run with the `task` utility: https://taskfile.dev/
version: '3'

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  VERSION: 1.0.0-dev

tasks:

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  build:
    cmds:
      - task: build-compress-path

  lint:
    cmds:
      - task: lint-compress-path

  lint-compress-path:
    desc: Runs golangci-lint
    sources:
      - './cmd/compress-path/**/*.go'
    cmds:
      - golangci-lint run ./cmd/compress-path

  build-compress-path:
    desc: Builds compress-path binary
    sources:
      - './cmd/compress-path/**/*.go'
    generates:
      - ./dist/compress-path
    cmds:
      - mkdir ./dist
      - go build -trimpath -ldflags="-s -w -X main.Version={{.VERSION}}-{{.GIT_COMMIT}}" -o dist ./cmd/compress-path

  install:
    desc: Installs the compress-path binary
    sources:
      - './dist/compress-path'
    cmds:
      - cp --force ./dist/compress-path $HOME/development/bin/compress-path
