# This file can be run with the `task` utility: https://taskfile.dev/
version: '3'

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  VERSION: 1.0.0-dev

tasks:

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  build:
    cmds:
      - task: build-{{project.name}}

  lint:
    cmds:
      - task: lint-{{project.name}}

  lint-{{project.name}}:
    desc: Runs golangci-lint
    sources:
      - './cmd/{{project.name}}/**/*.go'
    cmds:
      - golangci-lint run ./cmd/{{project.name}}

  build-{{project.name}}:
    desc: Builds {{project.name}} binary
    sources:
      - './cmd/{{project.name}}/**/*.go'
    generates:
      - ./dist/{{project.name}}
    cmds:
      - go build -trimpath -ldflags="-s -w -X main.Version={{.VERSION}}-{{.GIT_COMMIT}}" -o dist ./cmd/{{project.name}}
