# This file can be run with the `task` utility: https://taskfile.dev/
version: '3'

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  VERSION:
    sh: go run tools/build-version.go

tasks:

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Builds the binary
    cmds:
      - task: build-app

  clean:
    desc: Cleans up build artifacts
    cmds:
      - rm -f ./dist/compress-path
    preconditions:
      - test -f ./dist/compress-path

  lint:
    desc: Lints the code using golangci-lint
    cmds:
      - task: lint-app

  lint-app:
    desc: Runs golangci-lint
    cmds:
      - golangci-lint run ./cmd/compress-path

  build-app:
    desc: Builds compress-path binary
    deps:
      - task: update-version-file
    sources:
      - './cmd/compress-path/**/*.go'
    generates:
      - ./dist/compress-path
    cmds:
      - mkdir -p ./dist
      - go build -trimpath -ldflags="-s -w -X main.Version={{.VERSION}}-{{.GIT_COMMIT}}" -o dist ./cmd/compress-path

  update-version-file:
    cmds:
      - printf "package main\n\nvar Version = \"{{.VERSION}}\"" > ./cmd/compress-path/version.go
    status:
      - grep -q "\"{{.VERSION}}\"" ./cmd/compress-path/version.go

  install:
    desc: Installs the compress-path binary
    sources:
      - './dist/compress-path'
    cmds:
      - cp --force ./dist/compress-path $HOME/development/bin/compress-path
